# Generated by Django 4.2.30 on 2026-09-18 04:55

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('councilmatic_core', '0054_remove_person_councilmatic_biography_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OakParkBill',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('councilmatic_core.bill',),
        ),
        migrations.CreateModel(
            name='OakParkEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('councilmatic_core.event',),
        ),
        migrations.CreateModel(
            name='OakParkOrganization',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('councilmatic_core.organization',),
        ),
        migrations.CreateModel(
            name='OakParkPerson',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('councilmatic_core.person',),
        ),
    ]
